---
# tasks file for aci.
#- name: Import tasks of fabric configure.
#  ansible.builtin.include_tasks:
#    file: fabric.yml
#  tags: never
#
#- name: Import tasks of tenant configure.
#  ansible.builtin.include_tasks:
#    file: tenant.yml
#  tags: never
#
#- name: Import tasks of l3out configure.
#  ansible.builtin.include_tasks:
#    file: l3out.yml
#  tags: always
